# Generated by Django 3.2 on 2021-04-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tokens',
            field=models.JSONField(),
        ),
    ]
