# Generated by Django 3.2 on 2021-05-01 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_token_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='code',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tokens',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.token'),
        ),
    ]
