# Generated by Django 3.2 on 2021-05-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210501_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tokens',
        ),
        migrations.AddField(
            model_name='user',
            name='tokens',
            field=models.ManyToManyField(null=True, to='users.Token'),
        ),
    ]
