# Generated by Django 3.2 on 2021-04-30 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_tokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='tokens',
        ),
    ]
